export const formLoginController = [
    {
        name: 'email',
        label: 'Email',
        type: 'email',
        placeholder: 'Nhập Email',
        componentType: 'input',
        errorMessage1: 'Vui lòng nhập trường này',
        errorMessage2: 'Trường này là bắt buộc',
    },
    {
        name: 'password',
        label: 'Mật Khẩu',
        type: 'password',
        placeholder: 'Nhập password',
        componentType: 'input',
        errorMessage1: 'Vui lòng nhập trường này',
        errorMessage2: 'Nhập tối thiểu 6 ký tự',
    },
];

export const formRegisterController = [
    {
        name: 'username',
        label: 'Tên tài khoản',
        type: 'text',
        placeholder: 'Nhập tên tài khoản',
        componentType: 'input',
        errorMessage1: 'Vui lòng nhập trường này',
        errorMessage2: 'Trường này là bắt buộc',
    },
    {
        name: 'email',
        label: 'Email',
        type: 'email',
        placeholder: 'Nhập Email',
        componentType: 'input',
        errorMessage1: 'Vui lòng nhập trường này',
        errorMessage2: 'Trường này là bắt buộc',
    },
    {
        name: 'password',
        label: 'Mật Khẩu',
        type: 'password',
        placeholder: 'Nhập password',
        componentType: 'input',
        errorMessage1: 'Vui lòng nhập trường này',
        errorMessage2: 'Nhập tối thiểu 6 ký tự',
    },
];

export const formInformationUser = [
    {
        name: 'firstName',
        label: 'Họ và tên đệm',
        type: 'text',
        placeholder: 'Nhập tên họ và tên đệm',
        componentType: 'input',
        errorMessage1: 'Vui lòng nhập trường này',
        errorMessage2: 'Trường này là bắt buộc',
    },
    {
        name: 'lastName',
        label: 'Tên',
        type: 'text',
        placeholder: 'Nhập tên',
        componentType: 'input',
        errorMessage1: 'Vui lòng nhập trường này',
        errorMessage2: 'Trường này là bắt buộc',
    },
    {
        name: 'phone',
        label: 'Số Điện Thoại',
        type: 'text',
        placeholder: 'Nhập Số điện thoại',
        componentType: 'input',
        errorMessage1: 'Vui lòng nhập trường này',
        errorMessage2: 'Trường này là bắt buộc',
    },
    {
        name: 'email',
        label: 'Email',
        type: 'text',
        placeholder: 'Nhập email',
        componentType: 'input',
        errorMessage1: 'Vui lòng nhập trường này',
        errorMessage2: 'Trường này là bắt buộc',
    },
];

export const formAddressNew = [
    {
        name: 'firstName',
        label: 'Họ và tên đệm',
        type: 'text',
        placeholder: 'Nhập tên họ và tên đệm',
        componentType: 'input',
    },
    {
        name: 'lastName',
        label: 'Tên',
        type: 'text',
        placeholder: 'Nhập tên',
        componentType: 'input',
    },
    {
        name: 'phone',
        label: 'Số điện thoại',
        type: 'text',
        placeholder: 'Nhập Số điện thoại',
        componentType: 'input',
    },
    {
        name: 'detailAddress',
        label: 'Địa chỉ',
        type: 'text',
        placeholder: 'Nhập địa chỉ',
        componentType: 'input',
    },
];

export const formAddProduct = [
    {
        name: 'name',
        label: 'Tên sản phẩm',
        type: 'text',
        placeholder: 'Nhập tên sản phẩm',
        componentType: 'input',
    },
    {
        label: 'Tên thương hiệu',
        name: 'brand',
        componentType: 'select',
        options: [
            { id: 'HANOVER', label: 'HANOVER' },
            { id: 'HAVANA', label: 'HAVANA' },
            { id: 'LISBON', label: 'LISBON' },
            { id: 'KRAKOW', label: 'KRAKOW' },
            { id: 'DUSSELDORF', label: 'DUSSELDORF' },
            { id: 'SANTIAGO', label: 'SANTIAGO' },
            { id: 'STUTTGART', label: 'STUTTGART' },
            { id: 'ESSEN', label: 'ESSEN' },
            { id: 'HAMBURG', label: 'HAMBURG' },
            { id: 'BUDAPEST', label: 'BUDAPEST' },
            { id: 'WROCLAW', label: 'WROCLAW' },
            { id: 'DUBLIN', label: 'DUBLIN' },
            { id: 'NOWRA', label: 'NOWRA' },
            { id: 'LEEDS', label: 'LEEDS' },
            { id: 'MADRID', label: 'MADRID' },
            { id: 'OSLO', label: 'OSLO' },
            { id: 'CHICAGO', label: 'CHICAGO' },
            { id: 'SAN ANTONIO', label: 'SAN ANTONIO' },
            { id: 'PHOENIX', label: 'PHOENIX' },
            { id: 'HOUSTON', label: 'HOUSTON' },
        ],
    },
    {
        name: 'sale',
        label: 'Giá khuyến mãi',
        type: 'number',
        placeholder: 'Nhập giá khuyến mãi',
        componentType: 'input',
    },
    {
        name: 'price',
        label: 'Giá gốc',
        type: 'number',
        placeholder: 'Nhập giá gốc',
        componentType: 'input',
    },
    {
        name: 'introduce',
        label: 'Giới thiệu',
        type: 'textarea',
        placeholder: 'Giới thiệu sản phẩm',
        componentType: 'textarea',
    },
    {
        name: 'width',
        label: 'Chiều rộng',
        type: 'number',
        placeholder: 'Nhập Chiều rộng',
        componentType: 'input',
    },
    {
        name: 'height',
        label: 'Chiều cao',
        type: 'number',
        placeholder: 'Nhập chiều cao',
        componentType: 'input',
    },
    {
        name: 'length',
        label: 'Chiều dài',
        type: 'number',
        placeholder: 'Nhập chiều dài',
        componentType: 'input',
    },
    {
        name: 'material',
        label: 'Chất liệu',
        type: 'text',
        placeholder: 'Nhập chất liệu',
        componentType: 'input',
    },
    {
        name: 'infoDetailProduct',
        label: 'Chi tiết sản phẩm',
        type: 'textarea',
        placeholder: 'Chi tiết sản phẩm',
        componentType: 'textarea',
    },
    {
        name: 'infoEssential',
        label: 'Thông tin cần biết',
        type: 'textarea',
        placeholder: 'Thông tin cần biết',
        componentType: 'textarea',
    },
    {
        name: 'infoSafetyStandards',
        label: 'Tiêu chuẩn an toàn',
        type: 'textarea',
        placeholder: 'Tiêu chuẩn an toàn',
        componentType: 'textarea',
    },
    {
        name: 'infoFeatures',
        label: 'Tiện ích sản phẩm',
        type: 'textarea',
        placeholder: 'Tiện ích sản phẩm',
        componentType: 'textarea',
    },
];

export const formAddUser = [
    {
        name: 'username',
        label: 'Tên tài khoản',
        type: 'text',
        placeholder: 'Nhập tên tài khoản',
        componentType: 'input',
        errorMessage1: 'Vui lòng nhập trường này',
        errorMessage2: 'Trường này là bắt buộc',
    },
    {
        name: 'email',
        label: 'Email',
        type: 'email',
        placeholder: 'Nhập Email',
        componentType: 'input',
        errorMessage1: 'Vui lòng nhập trường này',
        errorMessage2: 'Trường này là bắt buộc',
    },
    {
        name: 'password',
        label: 'Mật Khẩu',
        type: 'password',
        placeholder: 'Nhập password',
        componentType: 'input',
        errorMessage1: 'Vui lòng nhập trường này',
        errorMessage2: 'Nhập tối thiểu 6 ký tự',
    },
    {
        name: 'phone',
        label: 'Số điện thoại',
        type: 'phone',
        placeholder: 'Nhập số điện thoại',
        componentType: 'input',
        errorMessage1: 'Vui lòng nhập trường này',
        errorMessage2: 'trường này là bắt buộc',
    },
];
